# theme: jekyll-theme-minimal
theme: mmistakes/minimal-mistakes
#remote_theme: daattali/beautiful-jekyll

markdown: kramdown
title: Basile Fraboni
description: Personal Website
url: "https://bfraboni.github.io"
