remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale                   : "fr-FR"
title                    : "Basile Fraboni"
subtitle                 : "Personal Website"
description              : "Personal Website"
url                      : https://bfraboni.github.io
repository               : "bfraboni/bfraboni.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"

markdown: kramdown
